### ISSUE TITLE
Network deadlocks on remote

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#1036]
### Brief summary

The browser test deadlocks on networking when more VUs are added.

Test run ID: 1944201 (prod).

### xk6-browser version

Remote

### OS

Remote

### Chrome version

Remote

### Steps to reproduce the problem

- Start a browser test with 24 browser VUs (I just modified the example script from the script editor to increase time to 20s and Vus to 24). I was attempting to run a test with more than one container.
- The test starts, but soon after, I get the error: timeout of 1m50s has expired.

### Expected behaviour

No deadlock.

### Actual behaviour

Further investigation is needed, but it seems like a network/communication problem:

```
github.com/grafana/xk6-browser/common.(*NetworkManager).handleEvents(0xc00904dce0, 0xc005aaf4a0)
    github.com/grafana/xk6-browser@v1.0.2/common/network_manager.go:308 +0x99 fp=0xc00426cfb0 sp=0xc00426cf18 pc=0x11e1299
github.com/grafana/xk6-browser/common.(*NetworkManager).initEvents.func1()
    github.com/grafana/xk6-browser@v1.0.2/common/network_manager.go:302 +0x37 fp=0xc00426cfe0 sp=0xc00426cfb0 pc=0x11e11d7
runtime.goexit()
    runtime/asm_amd64.s:1598 +0x1 fp=0xc00426cfe8 sp=0xc00426cfe0 pc=0x46fbe1
created by github.com/grafana/xk6-browser/common.(*NetworkManager).initEvents
    github.com/grafana/xk6-browser@v1.0.2/common/network_manager.go:301 +0x14d
goroutine 344777 [select, 4 minutes]:
runtime.gopark(0xc0083e2788?, 0x2?, 0x88?, 0x5a?, 0xc0083e277c?)
    runtime/proc.go:381 +0xd6 fp=0xc0083e2608 sp=0xc0083e25e8 pc=0x43bb16
runtime.selectgo(0xc0083e2788, 0xc0083e2778, 0x0?, 0x0, 0xc0072d2b40?, 0x1)
    runtime/select.go:327 +0x7be fp=0xc0083e2748 sp=0xc0083e2608 pc=0x44c1be
github.com/grafana/xk6-browser/common.(*BaseEventEmitter).syncAll(0xc0071cf180, {0x1a0c660, 0xc008141310})
    github.com/grafana/xk6-browser@v1.0.2/common/event_emitter.go:130 +0xab fp=0xc0083e27b8 sp=0xc0083e2748 pc=0x11a574b
github.com/grafana/xk6-browser/common.NewBaseEventEmitter.func1()
    github.com/grafana/xk6-browser@v1.0.2/common/event_emitter.go:120 +0x2e fp=0xc0083e27e0 sp=0xc0083e27b8 pc=0x11a566e
runtime.goexit()
    runtime/asm_amd64.s:1598 +0x1 fp=0xc0083e27e8 sp=0xc0083e27e0 pc=0x46fbe1
created by github.com/grafana/xk6-browser/common.NewBaseEventEmitter
    github.com/grafana/xk6-browser@v1.0.2/common/event_emitter.go:120 +0x1aa
```

**Comment by inancgumus** [comment]
Closed by #1072.
