### ISSUE TITLE
nil pointer: FrameManager.NavigateFrame

### ISSUE THREAD

**Issue by ka3de** [grafana/xk6-browser#1105]
### Brief summary

Nil pointer exception occurred in [FrameManager.NavigateFrame](https://github.com/grafana/xk6-browser/blob/d68946077680ff60f8b741f9305ce6dcde3fd78b/common/frame_manager.go#L588).

Test Run ID: 2094567

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x11e1f32]

goroutine 10318 [running]:
github.com/grafana/xk6-browser/common.(*FrameManager).NavigateFrame.func1({0x1489ce0?, 0xc001879880})
	github.com/grafana/xk6-browser@v1.1.1-0.20231026144352-d68946077680/common/frame_manager.go:588 +0x52
github.com/grafana/xk6-browser/common.createWaitForEventHandler.func1()
	github.com/grafana/xk6-browser@v1.1.1-0.20231026144352-d68946077680/common/helpers.go:145 +0x1e4
created by github.com/grafana/xk6-browser/common.createWaitForEventHandler in goroutine 10317
	github.com/grafana/xk6-browser@v1.1.1-0.20231026144352-d68946077680/common/helpers.go:137 +0x165
```

### xk6-browser version

v1.1.1

### OS

remote

### Chrome version

remote

### Steps to reproduce the problem

Run test locally.

### Expected behaviour

No panics.

### Actual behaviour

Panics.

**Comment by ka3de** [comment]
[NavigationEvent.newDocument](https://github.com/grafana/xk6-browser/blob/d68946077680ff60f8b741f9305ce6dcde3fd78b/common/event_emitter.go#L71) can be nil if the navigation happens within the same document. Having a pointer for the `newDocument` which can be `nil` can be problematic, as in this case, so maybe it would make sense to, instead of just having a single `navigation` [event](https://github.com/grafana/xk6-browser/blob/d68946077680ff60f8b741f9305ce6dcde3fd78b/common/event_emitter.go#L27), have a separate event for `navigationWithinDocument` and handle that from the event emitter?
