### ISSUE TITLE
Go panic: cannot create frame session

### ISSUE THREAD

**Issue by imiric** [grafana/xk6-browser#125]
We've been noticing this error recently from Tom's updated script:

```
ERRO[0014] unable to evaluate expression: Cannot find context with specified id (-32000)
running at reflect.methodValueCall (native)
default at file:///home/ivan/Projects/grafana/xk6-browser/examples/49-vistaprint-20211115.js:76:26(9)
        at go.k6.io/k6/js/common.Bind.func1 (native)
        at clickBusinessCards (file:///home/ivan/Projects/grafana/xk6-browser/examples/49-vistaprint-20211115.js:73:17(17))
        at file:///home/ivan/Projects/grafana/xk6-browser/examples/49-vistaprint-20211115.js:18:21(8)  executor=per-vu-iterations scenario=default source=stacktrace
WARN[0014]                                               category=cdp error="error fetching response body: context canceled" method=GET url="https://www.vistaprint.ca/visage/latest/v5/all/library/styles/components/core.ef3572a618c168760ba19432b84f7447.css"
panic: cannot create frame session: unable to add script to evaluate for isolated world: context canceled
running (00m13.4s), 1/1 VUs, 0 complete and 0 interrupted iterations
goroutine 52 [running]:--------------------------] 1 VUs  00m13.4s/10m0s  0/1 iters, 1 per VU
go.k6.io/k6/js/common.Throw(0x11203c0, {0x1585ca0, 0xc003298aa0})
        go.k6.io/k6@v0.35.0/js/common/util.go:36 +0x55
github.com/grafana/xk6-browser/common.k6Throw({0x15a57a8, 0xc0037d43c0}, {0x1328705, 0x1f}, {0xc002b49f30, 0x1, 0x1})
        github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/helpers.go:338 +0x1ae
github.com/grafana/xk6-browser/common.(*FrameSession).onAttachedToTarget(0xc003292280, 0xc003288400)
        github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/frame_session.go:653 +0x1d4
github.com/grafana/xk6-browser/common.(*FrcaameSession).initEvents.func1()
        github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/frame_session.go:217 +0x2f2
created by github.com/grafana/xk6-browser/common.(*FrameSession).initEvents
        github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/frame_session.go:180 +0xe7
```

The first `Cannot find context with specified id` is the same error from #49, but now it pretty much happens constantly. So yay, it can be reproduced :smile:

The second `cannot create frame session` panic is because the context was canceled. We're not sure if this is a regression or if a site change has exposed it. Regardless, it shouldn't happen.

**Comment by inancgumus** [comment]
I couldn't find the root cause of this after dealing with hundreds of print statements and debugging work.

@robingustafsson I need your help 🥺 

This is the latest debug output:

```
SESSION readLoop: sid: "B2B8BE926DD5919CE0E0E7F894F52A36", mid: 36, method: Page.lifecycleEvent


SESSION readLoop: sid: "B2B8BE926DD5919CE0E0E7F894F52A36", mid: 36, method: Page.lifecycleEvent


SESSION readLoop: sid: "B2B8BE926DD5919CE0E0E7F894F52A36", mid: 36, method: Network.responseReceived


SESSION readLoop: sid: "B2B8BE926DD5919CE0E0E7F894F52A36", mid: 36, method: Network.dataReceived


SESSION readLoop: sid: "B2B8BE926DD5919CE0E0E7F894F52A36", mid: 36, method: Network.loadingFinished

running (00m19.0s), 1/1 VUs, 0 complete and 0 interrupted iterations
SESSION readLoop: sid: "B2B8BE926DD5919CE0E0E7F894F52A36", mid: 36, method: Page.lifecycleEvent
ERRO[0020] unable to evaluate expression: Cannot find context with specified id (-32000)
running at reflect.methodValueCall (native)
default at file:///Users/inanc/grafana/tom-12nov.js:75:26(15)
	at go.k6.io/k6/js/common.Bind.func1 (native)
	at clickBusinessCards (file:///Users/inanc/grafana/tom-12nov.js:71:17(17))
	at file:///Users/inanc/grafana/tom-12nov.js:17:21(8)  executor=per-vu-iterations scenario=default source=stacktrace
panic: cannot create frame session: unable to add script to evaluate for isolated world: context canceled
running (00m19.1s), 1/1 VUs, 0 complete and 0 interrupted iterations
goroutine 86 [running]:--------------------------] 1 VUs  00m19.1s/10m0s  0/1 iters, 1 per VU
go.k6.io/k6/js/common.Throw(0x1d18c80, {0x217e0a0, 0xc0026c6440})
	go.k6.io/k6@v0.35.0/js/common/util.go:36 +0x55
github.com/grafana/xk6-browser/common.k6Throw({0x219dce8, 0xc0014549f0}, {0x1f2113f, 0x1f}, {0xc00032bf30, 0x1, 0x1})
	github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/helpers.go:354 +0x1ae
github.com/grafana/xk6-browser/common.(*FrameSession).onAttachedToTarget(0xc0033a8580, 0xc00057d400)
	github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/frame_session.go:659 +0x1d4
github.com/grafana/xk6-browser/common.(*FrameSession).initEvents.func1()
	github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/frame_session.go:222 +0x265
created by github.com/grafana/xk6-browser/common.(*FrameSession).initEvents
	github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/frame_session.go:180 +0xe7
```

**Comment by inancgumus** [comment]
I have a draft PR for this (not ready for review), working on it.

https://github.com/grafana/xk6-browser/tree/fix/125-frame-session-ctx-cancelled

I added a lot of logging statements to diagnose the root cause.

I finally determined that the context called error happens when we `sleep` in a script.

**Comment by inancgumus** [comment]
**Today's findings:**

* **Bad:** After adding a lot of log statements in this [PR](131), I can determine where and when the error occurs but still don't know the root cause.

* **Go test:** I [wrote a new test](https://github.com/grafana/xk6-browser/blob/28e81a61d318adf71eb68edcedf2af91f83181dc/tests/context_closed_test.go) in an experimental branch for validating the issue from the Go side. **The weird thing is that the test passes!**

* **Finding: Headless mode:** The issue doesn't occur in the headless mode.

* **Finding: Don't Sleep:** The issue doesn't occur if we don't sleep in the test code. I determined this yesterday as well, however, it should be the correct behavior for test scripts the follow which is "never sleep"! Note that _Playwright also recommends the same._
 
* **Finding: SlowMo:** I also determined that `SlowMo` breaks the scripts and results in the same error. So the problem may lie there. The websocket connection somehow drops, so I added a websocket keepaliver, but it didn't work, then I removed it.

* **Finding: Use `waitForSelector`:** So the test script works when it doesn't ever sleep but uses `waitForSelector` instead:

```javascript
import launcher from 'k6/x/browser';

let browser, context, page;

function initialize() {
  browser = launcher.launch('chromium', {
    debug: false,
    devtools: false,
    headless: false,
    slowMo: '500ms',
    timeout: '30s',
    // logCategoryFilter: 'Session:close|Connection|Frame',
  });

  context = browser.newContext({ });
  page = context.newPage();
}

export default function() {
  initialize();

  page.goto('https://vistaprint.ca', { waitUntil: 'domcontentloaded' });

  page.waitForSelector("//span[text()='Business Cards']");
  let elem = page.$("//span[text()='Business Cards']");
  elem.click();
  
  page.waitForSelector("//a[text()='Browse designs']");
  elem = page.$("//a[text()='Browse designs']");
  elem.click();  

  page.waitForSelector("li.design-tile");
  let elems = page.$$("li.design-tile");
  page.waitForSelector("li.design-tile");
}
```

@robingustafsson @imiric

**Comment by inancgumus** [comment]
I think I'm able to solve the error:
`panic: cannot create frame session: unable to add script to evaluate for isolated world: context canceled`.

Still no luck with the #49 's error of:
`Cannot find context with specified id`.

I guess I need to send a PR for the first error and track the second one in #49. No need to have double issues.

@imiric WDYT?

**Comment by inancgumus** [comment]
Playwright cannot run this script and randomly fails as well 🤷 

@tom-miseur can you provide us a script to reproduce the issue?

**We need a script that:**
* Works with Playwright (_that doesn't fail randomly_)
* Doesn't work with xk6-browser
* Doesn't use any external websites

So we can locally reproduce the problem and fix it if there is one.
