### ISSUE TITLE
`WaitFor` NPD

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#1319]
### What?

`WaitFor` generates an NPD when the execution context is not found.

```go
time="2024-05-09T08:32:41Z" level=error msg="error on evaluating window.k6SpanId: evaluating JS in global context: context canceled" category="FrameSession:onFrameNavigated" elapsed="0 ms" source=browser
--- FAIL: TestShadowDOMAndDocumentFragment (15.30s)
    --- FAIL: TestShadowDOMAndDocumentFragment/waitFor_DocumentFragment (0.47s)
        page_test.go:1697: 
            	Error Trace:	/home/runner/work/xk6-browser/xk6-browser/tests/page_test.go:1697
            	Error:      	Received unexpected error:
            	            	GoError: waiting for "//p[@id=\"inDocFrag\"]": getting new document handle: getting document element handle: Cannot find context with specified id at github.com/grafana/xk6-browser/common.(*Locator).WaitFor-fm (native)
            	Test:       	TestShadowDOMAndDocumentFragment/waitFor_DocumentFragment

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1ad8b1e]

goroutine 1310 [running]:
testing.tRunner.func1.2({0x1c0ba60, 0x2daa270})
	/opt/hostedtoolcache/go/1.21.10/x64/src/testing/testing.go:1545 +0x3f7
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.21.10/x64/src/testing/testing.go:1548 +0x716
panic({0x1c0ba60?, 0x2daa270?})
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:[92](https://github.com/grafana/xk6-browser/actions/runs/9014614523/job/24767627412?pr=1318#step:4:93)0 +0x270
github.com/grafana/xk6-browser/tests.TestShadowDOMAndDocumentFragment.func1(0x0?)
	/home/runner/work/xk6-browser/xk6-browser/tests/page_test.go:1698 +0x1fe
testing.tRunner(0xc00092a4e0, 0xc00096f7c0)
	/opt/hostedtoolcache/go/1.21.10/x64/src/testing/testing.go:15[95](https://github.com/grafana/xk6-browser/actions/runs/9014614523/job/24767627412?pr=1318#step:4:96) +0x262
created by testing.(*T).Run in goroutine 676
	/opt/hostedtoolcache/go/1.21.10/x64/src/testing/testing.go:1648 +0x846
FAIL	github.com/grafana/xk6-browser/tests	19.282s
FAIL
```

## Details
* [Test failure](https://github.com/grafana/xk6-browser/actions/runs/9014614523/job/24767627412?pr=1318)
* Version: v1.5.1

### Why?

Reliability.

### Tasks

```[tasklist]
### Tasks
- [ ] Subissue
- [ ] PR
- [ ] Docs PR
- [ ] TypeScript Definitions PR
- [ ] Update the k6 release notes
```

**Comment by ankur22** [comment]
I believe this was solved with https://github.com/grafana/xk6-browser/pull/1469
