### ISSUE TITLE
Concurrent map iteration and write

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#1375]
### What?

Fix the concurrent map iteration and map write bug.

Test run ID: 2760298

### Why?

To prevent the panic.

### How?

Fix the following bug:

```
fatal error: concurrent map iteration and map write

goroutine 94 [running]:
reflect.mapiternext(0x4b6aa9?)
runtime/map.go:1392 +0x13
reflect.(*MapIter).Next(0xc018d88680?)
reflect/value.go:2005 +0x74
internal/fmtsort.Sort({0x15a7760?, 0xc002cd2b60?, 0xc0012d1690?})
internal/fmtsort/sort.go:62 +0x1d3
fmt.(*pp).printValue(0xc000f94000, {0x15a7760?, 0xc002cd2b60?, 0x1?}, 0x76, 0x3)
fmt/print.go:816 +0x988
fmt.(*pp).printValue(0xc000f94000, {0x16f8d20?, 0xc002cd2b40?, 0xc018d88b28?}, 0x76, 0x2)
fmt/print.go:853 +0x11be
fmt.(*pp).printValue(0xc000f94000, {0x1750940?, 0xc002cd2b40?, 0xc01ae76000?}, 0x76, 0x1)
fmt/print.go:853 +0x11be
fmt.(*pp).printValue(0xc000f94000, {0x173a740?, 0xc002cd2b40?, 0x0?}, 0x76, 0x0)
fmt/print.go:921 +0xaf4
fmt.(*pp).badVerb(0xc000f94000, 0x71)
fmt/print.go:394 +0x47f
fmt.(*pp).fmtPointer(0xc000f94000, {0x173a740?, 0xc002cd2b40?, 0x50aa70?}, 0x71)
fmt/print.go:583 +0x414
fmt.(*pp).printValue(0xc000f94000, {0x173a740?, 0xc002cd2b40?, 0x50aa70?}, 0x71, 0x3)
fmt/print.go:927 +0x1165
fmt.(*pp).printValue(0xc000f94000, {0x17135e0?, 0xc014fefb80?, 0x0?}, 0x71, 0x2)
fmt/print.go:853 +0x11be
fmt.(*pp).printValue(0xc000f94000, {0x1646fa0?, 0xc014fefb80?, 0x50aa70?}, 0x71, 0x1)
fmt/print.go:853 +0x11be
fmt.(*pp).printValue(0xc000f94000, {0x17cb4c0?, 0xc014fefb80?, 0xc018d89970?}, 0x71, 0x0)
fmt/print.go:921 +0xaf4
fmt.(*pp).printArg(0xc000f94000, {0x17cb4c0, 0xc014fefb80}, 0x71)
fmt/print.go:759 +0x4bc
fmt.(*pp).doPrintf(0xc000f94000, {0x184d1e5, 0x45}, {0xc018d89de0, 0x4, 0x4})
fmt/print.go:1075 +0x37e
fmt.Errorf({0x184d1e5, 0x45}, {0xc018d89de0, 0x4, 0x4})
fmt/errors.go:25 +0x85
github.com/grafana/xk6-browser/common.(*ExecutionContext).eval(0xc018c3cfd0, {0x1bb8208, 0xc000ece730}, {0x1, 0x0}, {0x185895c, 0xa5}, {0xc0194d8a20, 0x6, 0x6})
github.com/grafana/xk6-browser@v1.5.1/common/execution_context.go:189 +0xd65
github.com/grafana/xk6-browser/common.(*ElementHandle).eval(...)
github.com/grafana/xk6-browser@v1.5.1/common/element_handle.go:1401
github.com/grafana/xk6-browser/common.(*ElementHandle).evalWithScript(0xc014fefb80, {0x1bb8208, 0xc000ece730}, {0x0?, 0x0?}, {0x185895c, 0xa5}, {0xc018d89f40, 0x4, 0x4})
github.com/grafana/xk6-browser@v1.5.1/common/element_handle.go:1392 +0x25d
github.com/grafana/xk6-browser/common.(*ElementHandle).waitForSelector(0xc014fefb80, {0x1bb8208, 0xc000ece730}, {0xc00258e3a8?, 0x1808d81?}, 0xc018d8a158)
github.com/grafana/xk6-browser@v1.5.1/common/element_handle.go:681 +0x188
github.com/grafana/xk6-browser/common.(*Frame).waitForSelector(0xc000a92540, {0xc00258e3a8, 0x11}, 0xc018d8a158)
github.com/grafana/xk6-browser@v1.5.1/common/frame.go:527 +0x1bb
github.com/grafana/xk6-browser/common.(*Frame).waitForSelectorRetry(0xc000a92540, {0xc00258e3a8, 0x11}, 0xc018d8a158, 0xc001b4a780?)
github.com/grafana/xk6-browser@v1.5.1/common/frame.go:511 +0x5a
github.com/grafana/xk6-browser/common.(*Frame).WaitForSelector(0xc000a92540, {0xc00258e3a8, 0x11}, {0x1bc9d18, 0xc001b4a780})
github.com/grafana/xk6-browser@v1.5.1/common/frame.go:1930 +0x165
github.com/grafana/xk6-browser/browser.mapFrame.func14({0xc00258e3a8?, 0x2?}, {0x1bc9d18?, 0xc001b4a780?})
github.com/grafana/xk6-browser@v1.5.1/browser/mapping.go:491 +0x45
reflect.Value.call({0x15a34a0?, 0xc000a87080?, 0x8?}, {0x17ec3d9, 0x4}, {0xc001b4a7e0, 0x2, 0xc0149663e0?})
reflect/value.go:596 +0xca6
reflect.Value.Call({0x15a34a0?, 0xc000a87080?, 0xc001b4a780?}, {0xc001b4a7e0?, 0xc00164ea10?, 0x7fcfca223bd8?})
reflect/value.go:380 +0xb9
github.com/dop251/goja.(*Runtime).newWrappedFunc.(*Runtime).wrapReflectFunc.func1({{0x1bc9d18, 0xc003544210}, {0xc0159497b8, 0x2, 0x2d}})
github.com/dop251/goja@v0.0.0-20240220182346-e401ed450204/runtime.go:1982 +0x3bd
github.com/dop251/goja.(*nativeFuncObject).vmCall(0xc0017be840, 0xc0034905a0, 0x2)
github.com/dop251/goja@v0.0.0-20240220182346-e401ed450204/func.go:563 +0x184
github.com/dop251/goja.call.exec(0x5?, 0xc0034905a0)
github.com/dop251/goja@v0.0.0-20240220182346-e401ed450204/vm.go:3375 +0x66
github.com/dop251/goja.(*vm).run(0xc0034905a0)
github.com/dop251/goja@v0.0.0-20240220182346-e401ed450204/vm.go:582 +0x5b
github.com/dop251/goja.(*vm).runTryInner(0xc018d8ac18?)
github.com/dop251/goja@v0.0.0-20240220182346-e401ed450204/vm.go:834 +0x65
github.com/dop251/goja.(*generator).step(0xc0009287e0)
github.com/dop251/goja@v0.0.0-20240220182346-e401ed450204/func.go:762 +0x2b
github.com/dop251/goja.(*asyncRunner).start(0xc0009287e0, 0x1)
github.com/dop251/goja@v0.0.0-20240220182346-e401ed450204/func.go:733 +0xfd
github.com/dop251/goja.(*baseJsFuncObject).asyncVmCall(0xc0032a5a40, 0xc0034905a0, 0x1, 0xc00164e990)
github.com/dop251/goja@v0.0.0-20240220182346-e401ed450204/func.go:664 +0x79
github.com/dop251/goja.(*asyncFuncObject).vmCall(0xc0032a5a40, 0xc0034905a0, 0x1)
github.com/dop251/goja@v0.0.0-20240220182346-e401ed450204/func.go:670 +0x65
github.com/dop251/goja.call.exec(0xd988e5?, 0xc0034905a0)
github.com/dop251/goja@v0.0.0-20240220182346-e401ed450204/vm.go:3375 +0x66
github.com/dop251/goja.(*vm).run(0xc0034905a0)
github.com/dop251/goja@v0.0.0-20240220182346-e401ed4502
```

### Tasks

```[tasklist]
### Tasks
- [ ] Subissue
- [ ] PR
- [ ] Docs PR
- [ ] TypeScript Definitions PR
- [ ] Update the k6 release notes
```

### Related PR(s)/Issue(s)

#1138

**Comment by inancgumus** [comment]
More of these occurred with these: 3395610, 3409489, 3409510, 3409521, 3409575, 3409583.

**Comment by inancgumus** [comment]
More: 3409521

**Comment by ankur22** [comment]
Test run: 3544658

```bash
fatal error: concurrent map writes

goroutine 3218 [running]:
github.com/grafana/sobek.(*templatedObject).getOwnPropStr(0xc00058c2d0, {0x1c2411b, 0x8})
github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/object_template.go:113 +0xb1
github.com/grafana/sobek.(*templatedObject).getStr(0xc00058c2d0, {0x1c2411b, 0x8}, {0x1faf738, 0xc0009ca360})
github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/object_template.go:92 +0x2c
github.com/grafana/sobek.(*baseObject).getStr(0xc0006375e0, {0x1c2411b, 0x8}, {0x0, 0x0})
github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/object.go:355 +0xbd
github.com/grafana/sobek.(*Object).tryPrimitive(0xc0009ca360, {0x1c2411b?, 0x2fba860?})
github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/object.go:840 +0x34
github.com/grafana/sobek.(*Object).ordinaryToPrimitiveString(0xc0009ca360)
github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/object.go:866 +0x28
github.com/grafana/sobek.(*Object).toPrimitiveString(0xc0009ca360)
github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/object.go:905 +0x3b
github.com/grafana/sobek.(*Object).String(0x2?)
github.com/grafana/sobek@v0.0.0-20241024150027-d91f02b05e9b/value.go:715 +0x13
github.com/grafana/xk6-browser/browser.mapPage.func11.1()
github.com/grafana/xk6-browser@v1.9.2-0.20241118153201-d741e4540a3a/browser/page_mapping.go:85 +0x43
github.com/grafana/xk6-browser/k6ext.promise.func1()
github.com/grafana/xk6-browser@v1.9.2-0.20241118153201-d741e4540a3a/k6ext/promise.go:24 +0x2c
created by github.com/grafana/xk6-browser/k6ext.promise in goroutine 78
github.com/grafana/xk6-browser@v1.9.2-0.20241118153201-d741e4540a3a/k6ext/promise.go:23 +0x9a

goroutine 1 [chan receive]:
go.k6.io/k6/execution.(*Scheduler).Run(0xc00011ea80, {0x1f9ad08, 0xc000292960}, {0x1f9acd0, 0xc00010c2a0}, 0xc000272620)
go.k6.io/k6/execution/scheduler.go:508 +0xcb4
go.k6.io/k6/cmd.(*cmdRun).run(0xc00028f2c0, 0xc0001fbb88, {0xc00038a008, 0x1, 0x2d})
go.k6.io/k6/cmd/run.go:397 +0x1545
github.com/spf13/cobra.(*Command).execute(0xc0001fbb88, {0xc0001b1b08, 0x2d, 0x2f})
github.com/spf13/cobra@v1.4.0/command.go:856 +0x68a
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001e8588)
github.com/spf13/cobra@v1.4.0/command.go:974 +0x38d
github.com/spf13/cobra.(*Command).Execute(...)
github.com/spf13/cobra@v1.4.0/command.go:902
go.k6.io/k6/cmd.(*rootCommand).execute(0xc0003f31a0)
go.k6.io/k6/cmd/root.go:108 +0xfb
go.k6.io/k6/cmd.Execute()
go.k6.io/k6/cmd/root.go:130 +0x2f
main.main()
go.k6.io/k6/main.go:9 +0xf

goroutine 8 [select]:
go.k6.io/k6/log.(*lokiHook).Listen(0xc00037ad00, {0x1f9ad08, 0xc000292910})
go.k6.io/k6/log/loki.go:220 +0x3dc
go.k6.io/k6/cmd.(*rootCommand).setLoggerHook.func1()
go.k6.io/k6/cmd/root.go:287 +0x2d
created by go.k6.io/k6/cmd.(*rootCommand).setLoggerHook in goroutine 1
go.k6.io/k6/cmd/root.go:286 +0xb0

goroutine 9 [select]:
io.(*pipe).read(0xc0000adc20, {0xc000400000, 0x10000, 0xc000082df0?})
io/pipe.go:57 +0xa5
io.(*PipeReader).Read(0xc000082e90?, {0xc000400000?, 0x0?, 0x10000?})
io/pipe.go:134 +0x1a
bufio.(*Scanner).Scan(0xc0002d5f28)
bufio/scan.go:219 +0x81e
github.com/sirupsen/logrus.(*Entry).writerScanner(0xc0001e6bd0, 0xc0000adc20, 0xc00028f750)
github.com/sirupsen/logrus@v1.9.3/writer.go:86 +0x11d
created by github.com/sirupsen/logrus.(*Entry).WriterLevel in goroutine 1
github.com/sirupsen/logrus@v1.9.3/writer.go:57 +0x31f

goroutine 10 [chan receive]:
go.k6.io/k6/cmd.(*rootCommand).setupLoggers.func2()
go.k6.io/k6/cmd/root.go:276 +0x34
created by go.k6.io/k6/cmd.(*rootCommand).setupLoggers in goroutine 1
go.k6.io/k6/cmd/root.go:275 +0x637

goroutine 20 [chan receive]:
go.k6.io/k6/log.(*lokiHook).Listen.func2()
go.k6.io/k6/log/loki.go:168 +0x10f
created by go.k6.io/k6/log.(*lokiHook).Listen in goroutine 8
go.k6.io/k6/log/loki.go:165 +0x2f9

goroutine 53 [chan receive]:
github.com/grafana/xk6-browser/browser.(*browserRegistry).handleIterEvents(0xc0000aca80, {0x1f9ab28, 0x2fd2b20}, 0xc000353650, 0xc0002df800)
github.com/grafana/xk6-browser@v1.9.2-0.20241118153201-d741e4540a3a/browser/registry.go:264 +0x85
created by github.com/grafana/xk6-browser/browser.newBrowserRegistry in goroutine 27
github.com/grafana/xk6-browser@v1.9.2-0.20241118153201-d741e4540a3a/browser/registry.go:251 +0x336

goroutine 11 [chan receive]:
github.com/grafana/xk6-browser/browser.(*browserRegistry).handleExitEvent(0xc000150cc0, 0x0?, 0x0?)
github.com/grafana/xk6-browser@v1.9.2-0.20241118153201-d741e4540a3a/browser/registry.go:333 +0x45
created by github.com/grafana/xk6-browser/browser.newBrowserRegistry in goroutine 1
github.com/grafana/xk6-browser@v1.9.2-0.20241118153201-d741e4540a3a/browser/registry.go:250 +0x2b2

goroutine 12 [chan receive]:
github.com/grafana/xk6-browser/browser.(*browserRegistry).handleIterEvents(0xc000150cc0, {0x1f9ab28, 0x2fd2b20}, 0xc0001e7f10, 0xc000028270)
github.com/grafana/xk6-browser@v1.9.2-0.20241118153201-d741e4540a3a/browser/registry.go:264 +0x85
created by github.com/grafana/xk6-browser/browser.newBrowserRegistry in goroutine 1
github.com/grafana/xk6-browser@v1.9.2-0.20241118153201-d741e
```
