### ISSUE TITLE
Unable to selectOption using object

### ISSUE THREAD

**Issue by pyrophos** [grafana/xk6-browser#1415]
### Brief summary

Unable to selectOption using object as described here: https://grafana.com/docs/k6/latest/javascript-api/k6-browser/locator/selectoption/
> If the select has the multiple attribute, all matching options are selected, otherwise only the first option matching one of the passed options is selected. Object can be made up of keys with value, label or index.

Supported by Playwright: https://playwright.dev/docs/input#select-options

Example: `options.selectOption({label:'Five'})`

### xk6-browser version

128.0.6613.115

### OS

Windows 11 Enterprise, 10.0.22631 Build 22631

### Chrome version

128.0.6613.115

### Steps to reproduce the problem

```
import { browser } from 'k6/browser';

export const options = {
  scenarios: {
    browser: {
      executor: 'shared-iterations',
      options: {
        browser: {
          type: 'chromium',
        },
      },
    },
  },
};

export default async function () {
  const page = await browser.newPage();
  await page.goto('https://test.k6.io/browser.php');
  const options = page.locator('#numbers-options');
  await options.selectOption({label:'Five'});
}
```

### Expected behaviour

Selecting "Five" from the numbers-options selection box

### Actual behaviour

```
panic: reflect: call of reflect.Value.Index on map Value
running (00m02.9s), 1/1 VUs, 0 complete and 0 interrupted iterations
goroutine 259 [running]:-------------------------] 1 VUs  00m02.9s/10m0s  0/1 shared iters
reflect.Value.Index({0x239ee60?, 0xc000567230?, 0xc000048460?}, 0xeea9fd?)
        reflect/value.go:1447 +0x154
github.com/grafana/xk6-browser/common.(*ElementHandle).selectOption.func1({0x29dafd8, 0xc000464ff0})
        github.com/grafana/xk6-browser@v1.7.0/common/element_handle.go:495 +0x828
github.com/grafana/xk6-browser/common.(*ElementHandle).selectOption(0xc000518640, {0x29c67f8, 0xc00046e2a0}, {0x29dafd8?, 0xc000464ff0?})
        github.com/grafana/xk6-browser@v1.7.0/common/element_handle.go:551 +0x63
github.com/grafana/xk6-browser/common.(*Frame).selectOption.func1({0x29c67f8?, 0xc00046e2a0?}, 0xc00046e2a0?)
        github.com/grafana/xk6-browser@v1.7.0/common/frame.go:1502 +0x34
github.com/grafana/xk6-browser/common.(*ElementHandle).newAction.func1({0x29c67f8, 0xc00046e2a0})
        github.com/grafana/xk6-browser@v1.7.0/common/element_handle.go:1545 +0x1b3
github.com/grafana/xk6-browser/common.(*ElementHandle).newAction.func2({0x29c67f8?, 0xc00046e2a0?}, 0xc0004e6720, 0xc0004e6780)
        github.com/grafana/xk6-browser@v1.7.0/common/element_handle.go:1560 +0x3b
github.com/grafana/xk6-browser/common.(*Frame).selectOption.(*Frame).newAction.func2({0x29c67f8, 0xc00046e2a0}, 0xc0004e6720, 0xc0004e6780)
        github.com/grafana/xk6-browser@v1.7.0/common/frame.go:2117 +0x178
created by github.com/grafana/xk6-browser/common.call in goroutine 258
        github.com/grafana/xk6-browser@v1.7.0/common/helpers.go:103 +0x14c
```

**Comment by ankur22** [comment]
I've taken a look at this issue, and at the moment we have a complicated way to convert the `Sobek.Value` to the desired type using reflection. It's very difficult to follow, error prone which can cause unexpected panics. Preferably it would be good to work with [exportTo](https://github.com/grafana/xk6-browser/blob/a87da04b549810e36399bf3888e35555dc8e6849/browser/helpers.go#L30).

The following is what we have [documented](https://grafana.com/docs/k6/latest/javascript-api/k6-browser/elementhandle/selectoption/) that should work:

```js
import { browser } from 'k6/browser';

export const options = {
  scenarios: {
    browser: {
      executor: 'shared-iterations',
      options: {
        browser: {
          type: 'chromium',
        },
      },
    },
  },
};

export default async function () {
  const page = await browser.newPage();
  await page.goto('https://test.k6.io/browser.php');
  const options = page.locator('#numbers-options');

  await options.selectOption({index:5});
  await options.selectOption({value:'five'});
  await options.selectOption({label:'Five'});
  await options.selectOption([{label:'Five'}]);
  await options.selectOption('Five'); // Value or label
  await options.selectOption(['Five']); // Value or label
}
```

I started exploring this with the following in [locator.selectOption](https://github.com/grafana/xk6-browser/blob/e8c6748041ab7b79770a31a10f8d2413d5e2b4fe/browser/locator_mapping.go#L133):

```go
				type asd struct {
					Value string `js:"value"`
					Label string `js:"label"`
					Index int    `js:"index"`
				}

				vObj, err := exportTo[asd](vu.Runtime(), values)
				if err != nil {
					return nil, fmt.Errorf("asd: %w", err)
				}
				fmt.Println("Test: object ", vObj)

				vSliceObj, err := exportTo[[]asd](vu.Runtime(), values)
				if err != nil {
					return nil, fmt.Errorf("asd: %w", err)
				}
				fmt.Println("Test: slice object ", vSliceObj)

				vSliceString, err := exportTo[[]string](vu.Runtime(), values)
				if err != nil {
					return nil, fmt.Errorf("asd: %w", err)
				}
				fmt.Println("Test: slice string ", vSliceString)

				vString, err := exportTo[string](vu.Runtime(), values)
				if err != nil {
					return nil, fmt.Errorf("asd: %w", err)
				}
				fmt.Println("Test: string ", vString)
```

I'm just not sure how best to detect which is the correct export value to use? When exporting to a string, and it returns [object Object] then that could be a sign that we need to move onto the next export.

Any ideas?

**Comment by inancgumus** [comment]
@ankur22 I'm not sure I understand the question: _"which is the correct export value to use"_?
