### ISSUE TITLE
`getOwnerFrame` `nil` pointer

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#1416]
### What?

Panic occurs while running `page.getOwnerFrame`, [here](https://github.com/grafana/xk6-browser/blob/cdbb2dd9b529215d564159698b0871a8ee3f5961/common/page.go#L444-L495):

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x138 pc=0x154713f]

goroutine 3623769 [running]:
github.com/grafana/xk6-browser/common.(*Page).getOwnerFrame(0xc04ef1fba0, {0x1eee958, 0xc133120cb0}, 0xc015ca2370)
github.com/grafana/xk6-browser@v1.7.1/common/page.go:489 +0x6bf
github.com/grafana/xk6-browser/common.(*ElementHandle).ownerFrame(0xc015ca2370, {0x1eee958?, 0xc133120cb0?})
github.com/grafana/xk6-browser@v1.7.1/common/element_handle.go:431 +0x45
github.com/grafana/xk6-browser/common.(*ElementHandle).checkHitTargetAt(0xc015ca2370, {0x1eee958?, 0xc133120cb0?}, {0x4084000000000000, 0x407cdf8000000000})
github.com/grafana/xk6-browser@v1.7.1/common/element_handle.go:67 +0x49
github.com/grafana/xk6-browser/common.(*ElementHandle).newPointerAction.func1({0x1eee958, 0xc133120cb0}, 0x0?)
github.com/grafana/xk6-browser@v1.7.1/common/element_handle.go:1621 +0x532
github.com/grafana/xk6-browser/common.retryPointerAction({0x1eee958, 0xc133120cb0}, 0xc1854851a0, 0xc06e7e01e0)
github.com/grafana/xk6-browser@v1.7.1/common/element_handle.go:1660 +0x3c
github.com/grafana/xk6-browser/common.(*ElementHandle).newPointerAction.func2({0x1eee958?, 0xc133120cb0?}, 0xc01f554ba0, 0xc01f554c60)
github.com/grafana/xk6-browser@v1.7.1/common/element_handle.go:1648 +0x45
github.com/grafana/xk6-browser/common.(*Frame).click.(*Frame).newPointerAction.func2({0x1eee958, 0xc133120cb0}, 0xc01f554ba0, 0xc01f554c60)
github.com/grafana/xk6-browser@v1.7.1/common/frame.go:2181 +0x116
created by github.com/grafana/xk6-browser/common.call in goroutine 3623768
github.com/grafana/xk6-browser@v1.7.1/common/helpers.go:103 +0x14c
```

---

* Test Run ID: 3207658
* k6 browser version: 1.7.1

### Why?

Needs to be investigated.

### Tasks

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/xk6-browser/pull/1435
- [ ] Update the k6 release notes
```

**Comment by ankur22** [comment]
I've investigated this issue and compared it with Playwright. Here are my findings:

The NPD currently can occur in [getOwnerFrame](https://github.com/grafana/xk6-browser/blob/d682cd6233939efcd3e3a2552f3038f4bafb9f53/common/page.go#L489). In Playwright, fortunately, they have an [equivalent method and they actually check for `null`](https://github.com/microsoft/playwright/blob/33890eb6c5298b239b42763e4652b3c7e40bf68f/packages/playwright-core/src/server/chromium/crPage.ts#L1110).

I think the safest option is to protect against a NPD here by also checking for `null`. Unfortunately, i've not been able to replicate the issue in the first place.

WDYT @inancgumus?

**Comment by inancgumus** [comment]
@ankur22 Sounds good to me 👍

**Comment by joanlopez** [comment]
Found another NPD that @ankur22 suggests it's similar to this one. Here are the details:

- Test Run ID: 3363010
- k6 browser version: 1.8.5

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x15924a8]

goroutine 368053 [running]:
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.deferwrap1()
go.opentelemetry.io/otel/sdk@v1.29.0/trace/span.go:398 +0x25
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc043cfcb60, {0x0, 0x0, 0xc01a2ae8c0?})
go.opentelemetry.io/otel/sdk@v1.29.0/trace/span.go:436 +0xa62
panic({0x1922540?, 0x2eb2e90?})
runtime/panic.go:785 +0x132
github.com/grafana/xk6-browser/common.(*screenshotter).screenshot(0xc049415eb0, {0x1f2ac00, 0xc014e5a0a0}, 0x0, 0xc049415ca8, {0x1bae2fb, 0x3}, 0x0, 0xc010762600?, {0xc013f74840, ...})
github.com/grafana/xk6-browser@v1.8.5/common/screenshotter.go:185 +0x328
github.com/grafana/xk6-browser/common.(*screenshotter).screenshotPage(0xc049415eb0, 0xc01ce864e0, 0xc010762580)
github.com/grafana/xk6-browser@v1.8.5/common/screenshotter.go:398 +0x334
github.com/grafana/xk6-browser/common.(*Page).Screenshot(0xc01ce864e0, 0xc010762580, {0x7f7cc4265108, 0xc001078540})
github.com/grafana/xk6-browser@v1.8.5/common/page.go:1146 +0x2c6
github.com/grafana/xk6-browser/browser.mapPage.func34.1()
github.com/grafana/xk6-browser@v1.8.5/browser/page_mapping.go:255 +0x4e
github.com/grafana/xk6-browser/k6ext.promise.func1()
github.com/grafana/xk6-browser@v1.8.5/k6ext/promise.go:41 +0x5a
created by github.com/grafana/xk6-browser/k6ext.promise in goroutine 108
github.com/grafana/xk6-browser@v1.8.5/k6ext/promise.go:40 +0xe6
```

Thanks! 🙇🏻

**Comment by ankur22** [comment]
@joanlopez, sorry, i meant https://github.com/grafana/xk6-browser/issues/1056 🤦

**Comment by ankur22** [comment]
@inancgumus I believe we can close this. I've not seen this issue since the fix. WDYT?

**Comment by inancgumus** [comment]
Sure, we can resurrect it if it happens again.
