### ISSUE TITLE
panic on getting title

### ISSUE THREAD

**Issue by mstoykov** [grafana/xk6-browser#1539]
### Brief summary

```
panic: interface conversion: interface {} is nil, not string

goroutine 4505318 [running]:
github.com/grafana/xk6-browser/common.(*Frame).Title(0xc048f0e540)
github.com/grafana/xk6-browser@v1.9.1/common/frame.go:1748 +0x132
github.com/grafana/xk6-browser/browser.mapFrame.func34.1()
github.com/grafana/xk6-browser@v1.9.1/browser/frame_mapping.go:233 +0x17
github.com/grafana/xk6-browser/k6ext.promise.func1()
github.com/grafana/xk6-browser@v1.9.1/k6ext/promise.go:24 +0x2c
created by github.com/grafana/xk6-browser/k6ext.promise in goroutine 409
github.com/grafana/xk6-browser@v1.9.1/k6ext/promise.go:23 +0x9a
```

### xk6-browser version

v1.9.1

### OS

linux

### Chrome version

-

### Steps to reproduce the problem

```javascript
import { browser } from "k6/browser";

export const options = {
	scenarios: {
		ui: {
			executor: "shared-iterations",
			options: {
				browser: {
					type: "chromium",
				},
			},
		},
	}
};

export default async function() {
	const context = await browser.newContext();
	const page = await context.newPage();
	page.frames()[0].title()
	console.log("here", page.mainFrame.title());
}
```

Seems to make it break in the same way - all lines seem to be improtant 

### Expected behaviour

no panic

### Actual behaviour

panic

**Comment by mstoykov** [comment]
This was fixed in 77a5872aa40b07e4338da44f226232c5946a2a48 but there was apperantly no issue that I can find.
