### ISSUE TITLE
TestPageGoto nil pointer error

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#186]
```
--- FAIL: TestPageGoto (0.38s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xff6bbb]

goroutine 10699 [running]:
testing.tRunner.func1.2({0x1681cc0, 0x2520ba0})
	/opt/hostedtoolcache/go/1.17.5/x64/src/testing/testing.go:1209 +0x36c
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.17.5/x64/src/testing/testing.go:1212 +0x3b6
panic({0x1681cc0, 0x2520ba0})
	/opt/hostedtoolcache/go/1.17.5/x64/src/runtime/panic.go:1047 +0x266
github.com/grafana/xk6-browser/common.(*Response).URL(0x0)
	/home/runner/work/xk6-browser/xk6-browser/common/response.go:351 +0x3b
github.com/grafana/xk6-browser/tests.TestPageGoto(0x0)
	/home/runner/work/xk6-browser/xk6-browser/tests/page_test.go:41 +0x139
testing.tRunner(0xc00315a1a0, 0x1843508)
	/opt/hostedtoolcache/go/1.17.5/x64/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.17.5/x64/src/testing/testing.go:1306 +0x727
FAIL	github.com/grafana/xk6-browser/tests	35.447s
```

Suspicious code:

https://github.com/grafana/xk6-browser/blob/ec037643fd1908ba5b6cadfb5e5d09b2fb9bfd92/common/response.go#L349-L352

**Comment by inancgumus** [comment]
Probably fixed.
