### ISSUE TITLE
CI: Frequent test timeouts

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#222]
This issue started to happen lately and I don't know the root cause. I receive `panic: test timed out after 1m0s` error almost after every push (See: [#1](https://github.com/grafana/xk6-browser/actions/runs/1806374714/attempts/1) and [#2](https://github.com/grafana/xk6-browser/actions/runs/1806374714/attempts/2)).

**Comment by inancgumus** [comment]
Happened again: https://github.com/grafana/xk6-browser/runs/5122002679?check_suite_focus=true

**Comment by imiric** [comment]
The linter runs in a separate job with a 3m timeout, so it's not that. The `NetworkManager` changes shouldn't have caused a delay, though the removal of goroutines in #217 might have.

Does it only happen on the job with coverage? Let's bump the coverage one to 3m and without to 2m?

**Comment by inancgumus** [comment]
> The NetworkManager changes shouldn't have caused a delay.

Maybe it's a coincidence, IDK. But note that this started happening even before #217.

> Does it only happen on the job with coverage? Let's bump the coverage one to 3m and without to 2m?

Happened with test-prev as well. Better increase all timeouts 5m or so, WDHT?

**Comment by imiric** [comment]
We don't have to keep wondering :smile:

<details>
<summary>Sorted test runtimes</summary>

```shell
$ git rev-parse HEAD
d9f551bc1566cbac8aa467402be61d897aee1af4

$ go test -v -race -count=1 -json ./... | tee test-results.json | jq -r '. | select(.Elapsed != null and .Test != null) | "\(.Test): \(.Elapsed)"' | sort -k2 -nr
TestLaunchOptionsSlowMo: 11.26
TestLaunchOptionsSlowMo/Frame: 5.8
TestLaunchOptionsSlowMo/Page: 5.32
TestPageScreenshotFullpage: 4.34
TestPageInputSpecialCharacters: 0.99
TestElementHandleClickWithNodeRemoved: 0.63
TestElementHandleClick: 0.59
TestElementHandleScreenshot: 0.58
TestPageInputValue: 0.56
TestLaunchOptionsSlowMo/Frame/hover: 0.55
TestElementHandleWaitForSelector: 0.54
TestLaunchOptionsSlowMo/Page/dblClick: 0.53
TestLaunchOptionsSlowMo/Frame/check: 0.53
TestLaunchOptionsSlowMo/Frame/dblClick: 0.52
TestPageIsChecked: 0.51
TestLaunchOptionsSlowMo/Page/check: 0.51
TestLaunchOptionsSlowMo/Page/click: 0.49
TestElementHandleInputValue: 0.49
TestLaunchOptionsSlowMo/Frame/click: 0.48
TestLaunchOptionsSlowMo/Frame/uncheck: 0.46
TestLaunchOptionsSlowMo/Page/hover: 0.45
TestLaunchOptionsSlowMo/Page/uncheck: 0.43
TestElementHandleClickWithDetachedNode: 0.42
TestLaunchOptionsSlowMo/Frame/selectOption: 0.41
TestElementHandleIsChecked: 0.41
TestElementHandleQueryAll: 0.4
TestLaunchOptionsSlowMo/Frame/type: 0.38
TestElementHandleBoundingBoxSVG: 0.38
TestPageEmulateMedia: 0.37
TestPageTitle: 0.36
TestLaunchOptionsSlowMo/Frame/press: 0.36
TestElementHandleGetAttribute: 0.34
TestPageGotoWaitUntilDOMContentLoaded: 0.33
TestLaunchOptionsSlowMo/Frame/setContent: 0.33
TestLaunchOptionsSlowMo/Frame/fill: 0.33
TestLaunchOptionsSlowMo/Page/press: 0.32
TestLaunchOptionsSlowMo/Frame/focus: 0.32
TestLaunchOptionsSlowMo/Frame/evaluateHandle: 0.32
TestBrowserContextOptionsExtraHTTPHeaders: 0.32
TestURLSkipRequest: 0.3
TestPageGotoWaitUntilLoad: 0.3
TestLaunchOptionsSlowMo/Frame/evaluate: 0.29
TestLaunchOptionsSlowMo/Frame/dispatchEvent: 0.29
TestElementHandleBoundingBoxInvisibleElement: 0.28
TestLaunchOptionsSlowMo/Page/selectOption: 0.27
TestPageSetExtraHTTPHeaders: 0.26
TestLaunchOptionsSlowMo/Page/type: 0.26
TestLaunchOptionsSlowMo/Page/dispatchEvent: 0.25
TestBlockIPs: 0.25
TestBlockHostnames: 0.25
TestPageGoto: 0.24
TestLaunchOptionsSlowMo/Frame/goto: 0.24
TestLaunchOptionsSlowMo/Page/setContent: 0.22
TestLaunchOptionsSlowMo/Page/fill: 0.22
TestPageGotoDataURI: 0.21
TestLaunchOptionsSlowMo/Page/focus: 0.21
TestLaunchOptionsSlowMo/Page/emulateMedia: 0.21
TestJSHandleGetProperties: 0.21
TestLaunchOptionsSlowMo/Page/goto: 0.2
TestBrowserNewPageInContext/timeout: 0.2
TestPageWaitForNavigationShouldNotPanic: 0.19
TestLaunchOptionsSlowMo/Page/reload: 0.19
TestLaunchOptionsSlowMo/Page/evaluateHandle: 0.19
TestBrowserNewPage: 0.19
TestLaunchOptionsSlowMo/Page/setViewportSize: 0.18
TestLaunchOptionsSlowMo/Page/evaluate: 0.18
TestBrowserContextOptionsSetViewport: 0.15
TestBrowserContextOptionsDefaultViewport: 0.14
TestFrameNilDocument: 0.1
TestBrowserVersion: 0.1
TestBrowserUserAgent: 0.1
TestElementHandleQueryAll/element_handle: 0.07
TestValueFromRemoteObject: 0.01
TestOnRequestPausedBlockedIPs: 0.01
TestOnRequestPausedBlockedHostnames: 0.01
TestElementHandleQueryAll/page: 0.01
TestElementHandleQueryAll/frame: 0.01
TestConvertArgument: 0.01
TestViewportCalculateInset/windows: 0
TestViewportCalculateInset/linux: 0
TestViewportCalculateInset/headless: 0
TestViewportCalculateInset/headful: 0
TestViewportCalculateInset/darwin: 0
TestViewportCalculateInset: 0
TestValueFromRemoteObject/unserializable_value_error: 0
TestValueFromRemoteObject/remote_object_with_ID: 0
TestValueFromRemoteObject/primitive_types: 0
TestValueFromRemoteObject/float64_unserializable_values: 0
TestValueFromRemoteObject/bigint_parsing_error: 0
TestTimeoutSettings/TimeoutSettings.timeout/should_work_with_parent: 0
TestTimeoutSettings/TimeoutSettings.timeout/should_work: 0
TestTimeoutSettings/TimeoutSettings.timeout: 0
TestTimeoutSettings/TimeoutSettings.setDefaultTimeout/should_work: 0
TestTimeoutSettings/TimeoutSettings.setDefaultTimeout: 0
TestTimeoutSettings/TimeoutSettings.setDefaultNavigationTimeout/should_work: 0
TestTimeoutSettings/TimeoutSettings.setDefaultNavigationTimeout: 0
TestTimeoutSettings/TimeoutSettings.NewTimeoutSettings/should_work_with_parent: 0
TestTimeoutSettings/TimeoutSettings.NewTimeoutSettings/should_work: 0
TestTimeoutSettings/TimeoutSettings.NewTimeoutSettings: 0
TestTimeoutSettings/TimeoutSettings.navigationTimeout/should_work_with_parent: 0
TestTimeoutSettings/TimeoutSettings.navigationTimeout/should_work: 0
TestTimeoutSettings/TimeoutSettings.navigationTimeout: 0
TestTimeoutSettings: 0
TestSessionCreateSession/send_and_recv_session_commands: 0
TestSessionCreateSession: 0
TestRequest/Size(): 0
TestRequest/HeaderValue(): 0
TestRequest/HeadersArray(): 0
TestRequest/Headers(): 0
TestRequest/error_parse_url: 0
TestRequest: 0
TestParseRemoteObject/nested: 0
TestParseRemoteObject/most_types: 0
TestParseRemoteObject/err_parsing_property: 0
TestParseRemoteObject/err_overflow: 0
TestParseRemoteObject: 0
TestOnRequestPausedBlockedIPs/ok_fail_simple: 0
TestOnRequestPausedBlockedIPs/ok_fail_resolved_ip: 0
TestOnRequestPausedBlockedIPs/ok_continue_simple: 0
TestOnRequestPausedBlockedIPs/ok_continue_resolved_ip: 0
TestOnRequestPausedBlockedIPs/ok_continue_empty: 0
TestOnRequestPausedBlockedHostnames/ok_fail_simple: 0
TestOnRequestPausedBlockedHostnames/ok_continue_simple: 0
TestOnRequestPausedBlockedHostnames/ok_continue_ip: 0
TestOnRequestPausedBlockedHostnames/ok_continue_empty: 0
TestOnRequestPausedBlockedHostnames/err_url_continue: 0
TestLaunchOptionsSlowMo/ElementHandle: 0
TestLaunchOptionsParse/args: 0
TestLaunchOptionsParse: 0
TestFrameManagerFrameAbortedNavigationShouldEmitANonNilPendingDocument: 0
TestEventEmitterSpecificEvent/remove_event_handler: 0
TestEventEmitterSpecificEvent/emit_event: 0
TestEventEmitterSpecificEvent/add_event_handler: 0
TestEventEmitterSpecificEvent: 0
TestEventEmitterAllEvents/remove_catch-all_event_handler: 0
TestEventEmitterAllEvents/emit_event: 0
TestEventEmitterAllEvents/add_catch-all_event_handler: 0
TestEventEmitterAllEvents: 0
TestErrorFromDOMError: 0
TestConvertArgument/string: 0
TestConvertArgument/int64_maxint: 0
TestConvertArgument/int64: 0
TestConvertArgument/float64_unserializable_values: 0
TestConvertArgument/float64: 0
TestConvertArgument/bool: 0
TestConvertArgument/*BaseJSHandle_wrong_context: 0
TestConvertArgument/*BaseJSHandle_is_disposed: 0
TestConvertArgument/*BaseJSHandle_as_*ElementHandle: 0
TestConvertArgument/*BaseJSHandle: 0
TestConsoleLogFormatter: 0
TestConnectionSendRecv/send_command_with_empty_reply: 0
TestConnectionSendRecv: 0
TestConnectionCreateSession/create_session_for_target: 0
TestConnectionCreateSession: 0
TestConnection/connect: 0
TestConnectionClosureAbnormal/closure_abnormal: 0
TestConnectionClosureAbnormal: 0
TestConnection: 0
TestBrowserTypeFlags/host-resolver-rules#01: 0
TestBrowserTypeFlags/host-resolver-rules: 0
TestBrowserTypeFlags/headless: 0
TestBrowserTypeFlags/enable-use-zoom-for-dsf: 0
TestBrowserTypeFlags/browser-arg-trim-single-quote: 0
TestBrowserTypeFlags/browser-arg-trim-double-quote: 0
TestBrowserTypeFlags/browser-args: 0
TestBrowserTypeFlags/browser-arg-flag: 0
TestBrowserTypeFlags/browser-arg: 0
TestBrowserTypeFlags/auto-open-devtools-for-tabs: 0
TestBrowserTypeFlags: 0
TestBrowserNewPageInContext/missing_browser_context: 0
TestBrowserNewPageInContext/happy_path: 0
TestBrowserNewPageInContext/error_in_create_target_action: 0
TestBrowserNewPageInContext/context_done: 0
TestBrowserNewPageInContext: 0
TestBrowserContextOptionsDefaultValues: 0
TestBarrier: 0
```

</details>

I didn't compare it to before the recent changes, but it might be good to run this in CI. I doubt #207 increased it, but #205 added a DNS lookup, though it's mocked in tests, so it shouldn't matter.

Anyway, sure, increasing it to 5m sounds good. You want to do that?

**Comment by inancgumus** [comment]
Oh, you like jq as much as I do, good job 👏  Including this in CI might be a good idea. However, the error tells us which test caused the issue:

<details>
<summary>Failure Message</summary>

```bash
panic: test timed out after 1m0s

goroutine 12155 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.17.6/x64/src/testing/testing.go:1788 +0xbb
created by time.goFunc
	/opt/hostedtoolcache/go/1.17.6/x64/src/time/sleep.go:180 +0x4a

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0000b31e0, {0x181a81c, 0x25}, 0x184ae10)
	/opt/hostedtoolcache/go/1.17.6/x64/src/testing/testing.go:1307 +0x752
testing.runTests.func1(0x0)
	/opt/hostedtoolcache/go/1.17.6/x64/src/testing/testing.go:1598 +0x9a
testing.tRunner(0xc0000b31e0, 0xc000521bc0)
	/opt/hostedtoolcache/go/1.17.6/x64/src/testing/testing.go:1259 +0x230
testing.runTests(0xc000358200, {0x253b7a0, 0x23, 0x23}, {0x0, 0xc00008b480, 0x2[548](https://github.com/grafana/xk6-browser/runs/5092943653?check_suite_focus=true#step:8:548)8a0})
	/opt/hostedtoolcache/go/1.17.6/x64/src/testing/testing.go:1596 +0x7cb
testing.(*M).Run(0xc000358200)
	/opt/hostedtoolcache/go/1.17.6/x64/src/testing/testing.go:1504 +0x9d2
main.main()
	_testmain.go:313 +0x32c

goroutine 19 [chan receive, 1 minutes]:
testing.(*T).Parallel(0xc0000b3380)

	/opt/hostedtoolcache/go/1.17.6/x64/src/testing/testing.go:1104 +0x48d
---------------------------------------- +
---------------------------------------- |
---------------------------------------- v
github.com/grafana/xk6-browser/tests.TestBrowserContextOptionsDefaultValues(0x0)
```
</details>

So, I'm not sure.

> Anyway, sure, increasing it to 5m sounds good. You want to do that?

Yeah, I'm going to bump them in a minute.

**Comment by imiric** [comment]
Hmm I doubt `TestBrowserContextOptionsDefaultValues` is the cause, rather it just happened to be running while something else was blocking it. Notice that it's stuck on `t.Parallel()`. It's a very simple test anyway, it doesn't initialize anything, while most of the stack traces are stuck at `BaseEventEmitter.syncAll()` and `common.contextWithDoneChan()`.

So this looks like an intermittent deadlock, it seems like we're not cancelling the main context somewhere, or just running tests with `t.Parallel()` too agressively. :thinking:

**Comment by inancgumus** [comment]
Yeah, it should be an issue from the combination of all tests/code. We removed `t.Parallel` from the tests before, but, of course, that still may be part of the deadlock issue, IDK.

> while most of the stack traces are stuck at BaseEventEmitter.syncAll() and common.contextWithDoneChan().

Those are used by almost every component in the system. There may be a bug in `syncAll` or some part of the code incorrectly uses it. `contextWithDoneChan` is simple enough. Like you said, maybe some part of the code doesn't cancel the context.

We need to further investigate.

**Comment by imiric** [comment]
Yeah, if it's a deadlock, increasing the timeout likely won't help, and we'll have to look into this sooner rather than later. But let's see. :crossed_fingers:
