### ISSUE TITLE
Cannot find context with specified id

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#49]
Reported by Tom on Oct, 30th:

* I was getting nil pointer exceptions here and somewhere here as a result of frame being nil. Moving the if blocks inside the preceding if `frame != nil` block got me past these. Not sure what the implications are beyond that though, but I guess having a nil frame is expected if there's already code checking for that condition?! :sweat_smile:
* Currently seeing a `ERRO[0026] unable to evaluate expression: Cannot find context with specified id (-32000)`. Not sure why - I think this was working before I pulled the latest `xk6-browser`.
* Also seeing a `panic: send on closed channel` but I think that might be happening as a result of earlier errors (like the above), i.e. during shutdown.

<details>
<summary>Example stack trace</summary>

```
panic: send on closed channel

goroutine 46 [running]:
go.k6.io/k6/stats.PushIfNotDone(...)
        go.k6.io/k6@v0.34.1/stats/stats.go:433
github.com/grafana/xk6-browser/common.(*NetworkManager).emitResponseReceived(0xc0010c0280, 0xc0006085b0)
        github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/network_manager.go:131 +0x87a
github.com/grafana/xk6-browser/common.(*NetworkManager).onResponseReceived(0xc0010c0280, 0xc0005de8c0)
        github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/network_manager.go:356 +0xc5
github.com/grafana/xk6-browser/common.(*NetworkManager).handleEvents(0xc0010c0280, 0xc00057a5a0)
        github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/network_manager.go:245 +0x1cf
github.com/grafana/xk6-browser/common.(*NetworkManager).initEvents.func1()
        github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/network_manager.go:220 +0x37
created by github.com/grafana/xk6-browser/common.(*NetworkManager).initEvents
        github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/network_manager.go:219 +0x125
```

</details>

Here's the JS code I'm running, with the failure happening in `clickBrowseDesigns` (which is odd as it is very similar to the preceding `clickBusinessCards`).

<details>

<summary>Script</summary>

```javascript
import { sleep, group } from 'k6';
import launcher from 'k6/x/browser';

import { randomIntBetween } from 'https://jslib.k6.io/k6-utils/1.1.0/index.js';

export const options = {};

let browser, context, page;

const pauseMin = 1;
const pauseMax = 1;

export default function() {
  initialize();
  
  navigateToHomepage();
  clickBusinessCards();
  clickBrowseDesigns();
  clickDesign('Standard (3.5" x 2")');
}

function initialize() {
  browser = launcher.launch('chromium', {
    args: [],
    debug: false,
    devtools: false,
    env: {},
    executablePath: null,
    headless: false,
    ignoreDefaultArgs: [],
    proxy: {},
    slowMo: '500ms',
    timeout: '30s',
  });

  context = browser.newContext({
    ignoreHTTPSErrors: true
  });

  page = context.newPage();
}

function navigateToHomepage() {
  group("Navigate to Homepage", () => {
    page.goto('https://vistaprint.ca', { waitUntil: 'domcontentloaded' });
  });

  sleep(randomIntBetween(pauseMin, pauseMax));
}

function clickBusinessCards() {
  const elem = page.$("//span[text()='Business Cards']");

  console.log(JSON.stringify(elem));

  group("Click Business Cards", () => {
    elem.click();
    
    // Wait for next page to load
    page.waitForLoadState('networkidle');
  });

  sleep(randomIntBetween(pauseMin, pauseMax));
}

function clickBrowseDesigns() {
  const elem = page.$("//a[text()='Browse designs']");

  console.log(JSON.stringify(elem));

  group("Click Browse Designs", () => {
    elem.click();
    
    page.waitForLoadState('networkidle');
  });

  sleep(randomIntBetween(pauseMin, pauseMax));
}

function clickDesign(designName) {
  // fetch all of the design options
  const designOptions = page.$("li.design-tile");
  console.log(JSON.stringify(designOptions));
  console.log(`Found ${designOptions.length} design options.`);

  console.log(`Selecting "${designName}"...`);

  JSON.stringify(designOptions);
}
```

</details>

---

[This PR](https://github.com/grafana/xk6-browser/pull/50) fixes the `nil pointer` issues.

**Comment by inancgumus** [comment]
On hold because: https://github.com/grafana/xk6-browser/issues/125#issuecomment-986701327

**Comment by inancgumus** [comment]
I couldn't help and tried some to fix this again, but still no luck 😢

**Comment by inancgumus** [comment]
Update:

I found some subtle bugs that are easy to miss. I'll add my findings here soon.
