### ISSUE TITLE
Some Locator tests are flaky

### ISSUE THREAD

**Issue by imiric** [grafana/xk6-browser#494]
Locator tests sometimes fail in CI on current `main` (c7b281b), though we haven't been able to reproduce it locally.

For example: [#1212](https://github.com/grafana/xk6-browser/runs/7790458597), [#1216](https://github.com/grafana/xk6-browser/runs/7803589655)

```
    --- FAIL: TestLocatorElementState/disabled (30.42s)
panic: checking is "#inputText" visible: timed out after 30s [recovered]
	panic: checking is "#inputText" visible: timed out after 30s

goroutine 17394 [running]:
testing.tRunner.func1.2({0x1a19da0, 0xc008665980})
	/home/runner/sdk/gotip/src/testing/testing.go:1396 +0x372
testing.tRunner.func1()
	/home/runner/sdk/gotip/src/testing/testing.go:1399 +0x5f0
panic({0x1a19da0, 0xc008665980})
	/home/runner/sdk/gotip/src/runtime/panic.go:890 +0x262
go.k6.io/k6/js/common.Throw(0x35?, {0x1c9f2e0?, 0xc004c9d260})
	/home/runner/go/pkg/mod/go.k6.io/k6@v0.39.0/js/common/util.go:40 +0x85
github.com/grafana/xk6-browser/k6ext.Panic({0x1cacb00, 0xc0039ba000}, {0x1a72274, 0x1a}, {0xc003a7bd68, 0x2, 0x2})
	/home/runner/work/xk6-browser/xk6-browser/k6ext/panic.go:51 +0x418
github.com/grafana/xk6-browser/common.(*Locator).IsVisible(0xc00404ea50, {0x0?, 0x0})
	/home/runner/work/xk6-browser/xk6-browser/common/locator.go:240 +0x557
github.com/grafana/xk6-browser/tests.TestLocatorElementState.func5({0x1cb9538, 0xc00404ea50})
	/home/runner/work/xk6-browser/xk6-browser/tests/locator_test.go:307 +0x42
github.com/grafana/xk6-browser/tests.TestLocatorElementState.func6(0x0?)
	/home/runner/work/xk6-browser/xk6-browser/tests/locator_test.go:320 +0x1b2
testing.tRunner(0xc0041a0680, 0xc004a6b790)
	/home/runner/sdk/gotip/src/testing/testing.go:1446 +0x217
created by testing.(*T).Run
	/home/runner/sdk/gotip/src/testing/testing.go:1493 +0x75e
FAIL	github.com/grafana/xk6-browser/tests	74.872s
```

I've noticed other Locator tests failing before as well. This is unlikely to be caused by the recent Locator changes, but by an existing underlying race condition.

**Comment by inancgumus** [comment]
They are no longer flaky, so closing the issue. @grafana/k6-browser WDYT? Please tag me when replying, so I can get a notification.

**Comment by ankur22** [comment]
@inancgumus happy to close this

**Comment by inancgumus** [comment]
We no longer witness this flaky test on CI, closing as not planned.
