### ISSUE TITLE
Nil when getting the `DocumentID`

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#577]
Version: https://github.com/grafana/xk6-browser/commit/508bcb861edcdad7615e53cbf64c3829b4dfd0b3
Script: Complex script

At a certain point (always seems to be different, so it looks to be a race issue) I get:

```
running (00m07.0s), 1/1 VUs, 0 complete and 0 interrupted iterations
default   [   0% ] 1 VUs  00m07.0s/10m0s  0/1 shared iters
time="2022-10-10T17:51:51+01:00" level=info msg="\"@vp/tracking:7.0.1050\"" source=browser-console-api
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x68 pc=0x1013534b8]

goroutine 8117 [running]:
github.com/grafana/xk6-browser/common.(*Request).getDocumentID(...)
        github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/request.go:136
github.com/grafana/xk6-browser/common.(*NetworkManager).onLoadingFinished(0x14002153260, 0x14000c64990)
        github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/network_manager.go:400 +0x68
github.com/grafana/xk6-browser/common.(*NetworkManager).handleEvents(0x14002153260, 0x1400411e000)
        github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/network_manager.go:364 +0x140
github.com/grafana/xk6-browser/common.(*NetworkManager).initEvents.func1()
        github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/network_manager.go:345 +0x3c
created by github.com/grafana/xk6-browser/common.(*NetworkManager).initEvents
        github.com/grafana/xk6-browser@v0.0.0-00010101000000-000000000000/common/network_manager.go:344 +0x160
2022/10/10 17:51:52 [ERROR] exit status 2
```
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/xk6-browser/pull/1163
- [ ] https://github.com/grafana/k6/pull/3579
```

**Comment by ankur22** [comment]
I've taken a look at the code and can see that it's a similar scenario to https://github.com/grafana/xk6-browser/issues/1148 where it's easy to forget to check for the `nil` value before using it. I've audited the areas of the code that work with [requestFromID](https://github.com/grafana/xk6-browser/blob/5f754c2c2252896016fd77d1fd3234a795049a0e/common/network_manager.go#L642) (which was used to get the `request` that then led to a NPD when calling `request. getDocumentID`), and it looks like the correct `nil` checks are now in place. Nevertheless, I'll change the method signature of `requestFromID` so that it also returns a `bool` indicating whether the value was retrieved or not so that we don't make the same mistake again.
