### ISSUE TITLE
Running 50 browser VUs using per-vu-iterations caused VUs to drop and halted execution

### ISSUE THREAD

**Issue by mdcruz** [grafana/xk6-browser#602]
### Brief summary

Running 50 browser VUs using per-vu-iterations caused VUs to drop and halted execution after 3 mins. There were also a high amount of errors reported in the console (see logs in actual behaviour)

### xk6-browser version

xk6-browser pre-v0.6.0

### OS

macOS 12.6

### Chrome version

105.0.5195.125

### Steps to reproduce the problem

Run the following script in k6 Staging cloud:

```
import { check, sleep } from 'k6';
import { chromium } from 'k6/x/browser';

export const options = {
 scenarios: {
   messages: {
     executor: 'per-vu-iterations',
     vus: 50,
     maxDuration: '5m',
     iterations: '10'
   }
 }
};

export default function () {
 const browser = chromium.launch();
 const page = browser.newPage();

 page.goto('https://test.k6.io/my_messages.php', { waitUntil: 'networkidle' }).then(() => {
   sleep(1);
   // Enter login credentials and login
   page.locator('input[name="login"]').type('admin');
   page.locator('input[name="password"]').type('123');

   sleep(1);

   // Wait for asynchronous operations to complete
   return Promise.all([
     page.waitForNavigation(),
     page.locator('input[type="submit"]').click(),
   ]).then(() => {
     check(page, {
       'header': page.locator('h2').textContent() == 'Welcome, admin!',
     });
   }).finally(() => {
     page.close();
     browser.close();
   });
 });
}
```

### Expected behaviour

Test should run and metrics are reported to k6 cloud

### Actual behaviour

There were some drops and pauses in the execution after 3 mins, and a high number of errors were reported in the console log.

<img width="1275" alt="Screenshot 2022-10-24 at 12 00 02" src="https://user-images.githubusercontent.com/10811379/197511373-0afe14d1-1100-40d5-a067-528737dae928.png">

Logs from console:

```
      /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io

  execution: cloud
     script: examples/sample.test.js
     output: https://app.k6.io/runs/141588

  scenarios: (100.00%) 1 scenario, 50 max VUs, 5m30s max duration (incl. graceful stop):
           * messages: 10 iterations for each of 50 VUs (maxDuration: 5m0s, gracefulStop: 30s)

ERRO[0073] communicating with browser: read tcp 127.0.0.1:53220->127.0.0.1:18509: read: connection reset by peer category=cdp elapsed=78 ms goroutine=534  instance_id=0 lz="amazon:us:columbus" test_run_id=141588
ERRO[0073] process with PID 1954 unexpectedly ended: context deadline exceeded category=browser elapsed=24 ms goroutine=238  instance_id=0 lz="amazon:us:columbus" test_run_id=141588
ERRO[0073] communicating with browser: read tcp 127.0.0.1:6484->127.0.0.1:32371: read: connection reset by peer category=cdp elapsed=135 ms goroutine=602  instance_id=0 lz="amazon:us:columbus" test_run_id=141588
ERRO[0073] process with PID 2112 unexpectedly ended: context deadline exceeded category=browser elapsed=267 ms goroutine=301  instance_id=0 lz="amazon:us:columbus" test_run_id=141588
WARN[0073] k6 dropped 51 log messages because they were above the limit of 10 messages / 1s  instance_id=0 lz="amazon:us:columbus" test_run_id=141588
ERRO[0074] process with PID 2165 unexpectedly ended: signal: killed category=browser elapsed=180 ms goroutine=326  instance_id=0 lz="amazon:us:columbus" test_run_id=141588
ERRO[0074] Uncaught (in promise) GoError: getting text content of "h2": read tcp 127.0.0.1:53220->127.0.0.1:18509: read: connection reset by peer: GoError
Run    [at reflect.methodValueCall (native)
        at file:///Users/nobody/Documents/xk6-browser/xk6-browser-example/examples/sample.test.js:33:31(10)
        at native

 executor=per-vu-iterations scenario=messages  instance_id=0 lz="amazon:us:columbus" test_run_id=141588
ERRO[0074] communicating with browser: websocket: close 1006 (abnormal closure): unexpected EOF category=cdp elapsed=0 ms goroutine=691  instance_id=0 lz="amazon:us:columbus" test_run_id=141588
ERRO[0074] communicating with browser: websocket: close 1006 (abnormal closure): unexpected EOF category=cdp elapsed=381 ms goroutine=464  instance_id=0 lz="amazon:us:columbus" test_run_id=141588
ERRO[0074] process with PID 1899 unexpectedly ended: context deadline exceeded category=browser elapsed=486 ms goroutine=243  instance_id=0 lz="amazon:us:columbus" test_run_id=141588
ERRO[0074] process with PID 1991 unexpectedly ended: signal: killed category=browser elapsed=299 ms goroutine=266  instance_id=0 lz="amazon:us:columbus" test_run_id=141588
ERRO[0074] communicating with browser: websocket: close 1006 (abnormal closure): unexpected EOF category=cdp elapsed=41 ms goroutine=731  instance_id=0 lz="amazon:us:columbus" test_run_id=141588
ERRO[0074] process with PID 1981 unexpectedly ended: context deadline exceeded category=browser elapsed=284 ms goroutine=260  instance_id=0 lz="amazon:us:columbus" test_run_id=141588
ERRO[0074] communicating with browser: read tcp 127.0.0.1:58892->127.0.0.1:15455: read: connection reset by peer category=cdp elapsed=599 ms goroutine=590  instance_id=0 lz="amazon:us:columbus" test_run_id=141588
ERRO[0074] process with PID 2021 unexpectedly ended: signal: killed category=browser elapsed=203 ms goroutine=286  instance_id=0 lz="amazon:us:columbus" test_run_id=141588
ERRO[0074] communicating with browser: websocket: close 1006 (abnormal closure): unexpected EOF category=cdp elapsed=167 ms goroutine=749  instance_id=0 lz="amazon:us:columbus" test_run_id=141588
ERRO[0074] process with PID 2088 unexpectedly ended: signal: killed category=browser elapsed=12 ms goroutine=310  instance_id=0 lz="amazon:us:columbus" test_run_id=141588
ERRO[0074] Uncaught (in promise) GoError: getting text content of "h2": websocket: close 1006 (abnormal closure): unexpected EOF: GoError
Run    [at reflect.methodValueCall (native)
        at file:///Users/nobody/Documents/xk6-browser/xk6-browser-example/examples/sample.test.js:33:31(10)
        at native

 executor=per-vu-iterations scenario=messages  instance_id=0 lz="amazon:us:columbus" test_run_id=141588
ERRO[0074] process with PID 1857 unexpectedly ended: signal: killed category=browser elapsed=93 ms goroutine=201  instance_id=0 lz="amazon:us:columbus" test_run_id=141588
ERRO[0074] Uncaught (in promise) GoError: getting text content of "h2": read tcp 127.0.0.1:62886->127.0.0.1:18357: read: connection reset by peer: GoError
Run    [at reflect.methodValueCall (native)
        at file:///Users/nobody/Documents/xk6-browser/xk6-browser-example/examples/sample.test.js:33:31(10)
        at native

 executor=per-vu-iterations scenario=messages  instance_id=0 lz="amazon:us:columbus" test_run_id=141588
ERRO[0074] process with PID 2031 unexpectedly ended: signal: killed category=browser elapsed=149 ms goroutine=283  instance_id=0 lz="amazon:us:columbus" test_run_id=141588
WARN[0074] k6 dropped 10 log messages because they were above the limit of 10 messages / 1s  instance_id=0 lz="amazon:us:columbus" test_run_id=141588

Run    [======================================] Finished
     test status: Finished

Run    [======================================] Finished
```

**Comment by imiric** [comment]
This is related to https://github.com/grafana/xk6-browser/issues/601#issuecomment-1288894280, and I suggest closing this issue as well.

50 browser VUs on a `t5.large` instance is still too high. A reasonable limit should be around 10-20 VUs, and depending on the site, maybe even less than that.

**Comment by mdcruz** [comment]
> This is related to [#601 (comment)](https://github.com/grafana/xk6-browser/issues/601#issuecomment-1288894280), and I suggest closing this issue as well.
> 
> 50 browser VUs on a `t5.large` instance is still too high. A reasonable limit should be around 10-20 VUs, and depending on the site, maybe even less than that.

Closing this one too as running it distributed on two zones worked.
<img width="1326" alt="Screenshot 2022-10-24 at 15 55 08" src="https://user-images.githubusercontent.com/10811379/197557554-7cfc1fb4-47e4-4870-b033-09cc58757dd0.png">
