### ISSUE TITLE
ExecutionContext: nil pointer

### ISSUE THREAD

**Issue by inancgumus** [grafana/xk6-browser#75]
```
=== RUN   TestPageGoto/Page.goto/should_work
time="2021-11-08T23:17:01+03:00" level=warning msg="error fetching response body: No data found for resource with given identifier (-32000)" category=cdp elapsed="0 ms" goroutine=20643
=== RUN   TestPageGoto/Page.goto/should_wait_for_load_event
=== RUN   TestPageGoto/Page.goto/should_wait_for_domcontentloaded_event
time="2021-11-08T23:17:02+03:00" level=warning msg="error fetching response body: No data found for resource with given identifier (-32000)" category=cdp elapsed="0 ms" goroutine=20951
--- FAIL: TestPageGoto (2.13s)
    --- FAIL: TestPageGoto/Page.goto (1.50s)
        --- PASS: TestPageGoto/Page.goto/should_work (0.64s)
        --- PASS: TestPageGoto/Page.goto/should_wait_for_load_event (0.38s)
        --- FAIL: TestPageGoto/Page.goto/should_wait_for_domcontentloaded_event (0.48s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1cc5e4b]

goroutine 20941 [running]:
testing.tRunner.func1.2(0x2446e20, 0x31b61b0)
	/usr/local/go/src/testing/testing.go:1143 +0x49f
testing.tRunner.func1(0xc001b44a80)
	/usr/local/go/src/testing/testing.go:1146 +0x695
panic(0x2446e20, 0x31b61b0)
	/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/grafana/xk6-browser/common.(*ExecutionContext).evaluate(0x0, 0x27bae00, 0xc004e09650, 0x25c0101, 0x27c76c8, 0xc00500e4d0, 0x0, 0x0, 0x0, 0xc002cabd08, ...)
	/Users/inanc/xk6-browser/common/execution_context.go:150 +0x38b
github.com/grafana/xk6-browser/common.(*ExecutionContext).Evaluate(...)
	/Users/inanc/xk6-browser/common/execution_context.go:199
github.com/grafana/xk6-browser/common.(*Frame).Evaluate(0xc002dd1a00, 0x27c76c8, 0xc00500e4d0, 0x0, 0x0, 0x0, 0x27c81b8, 0xc000656540)
	/Users/inanc/xk6-browser/common/frame.go:638 +0x19a
github.com/grafana/xk6-browser/common.(*Page).Evaluate(0xc003d7ed80, 0x27c76c8, 0xc00500e4d0, 0x0, 0x0, 0x0, 0xc000656540, 0xc00178fe00)
	/Users/inanc/xk6-browser/common/page.go:372 +0xb3
github.com/grafana/xk6-browser/tests.testPageGotoWaitUntilDOMContentLoaded(0xc001b44a80, 0xc002af8ac0)
	/Users/inanc/xk6-browser/tests/page_goto_test.go:85 +0x2c4
github.com/grafana/xk6-browser/tests.TestPageGoto.func1.3(0xc001b44a80)
	/Users/inanc/xk6-browser/tests/page_goto_test.go:41 +0x4c
testing.tRunner(0xc001b44a80, 0xc003993a30)
	/usr/local/go/src/testing/testing.go:1193 +0x203
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x5d8
FAIL	github.com/grafana/xk6-browser/tests	112.587s
```

**Comment by inancgumus** [comment]
Weird, I can no longer reproduce this locally...

**Comment by imiric** [comment]
Closing this since we haven't run into it recently.
