### ISSUE TITLE
creating new page in browser context: timed out after 30s

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#966]
### Brief summary

When running tests against a remote chrome instance(s) we see the following error:

```bash
Uncaught (in promise) GoError: creating new page in browser context: timed out after 30s
	at github.com/grafana/xk6-browser/browser.mapBrowserContext.func4 (native)
	at file:///tmp/TgCEDu/script.js:24:15(8)
 executor=shared-iterations scenario=ui
```

This doesn't occur when running against a locally running chrome instance.

### xk6-browser version

a8ebe8cc24f639e0553b1d969df97368db7b5ec5

### OS

NA

### Chrome version

NA

### Docker version and image (if applicable)

NA

### Steps to reproduce the problem

When running the following script against a single remote chrome instance:

```js
import { check } from 'k6';
import { browser } from 'k6/experimental/browser';

export const options = {
  scenarios: {
    ui: {
      executor: 'shared-iterations',
      vus: 10,
      iterations: 100,
      options: {
        browser: {
          type: 'chromium',
        },
      },
    },
  },
  thresholds: {
    checks: ["rate==1.0"]
  }
}

export default async function () {
  const context = browser.newContext();
  const page = context.newPage();

  try {
    // Goto front page, find login link and click it
    await page.goto('https://test.k6.io/', { waitUntil: 'networkidle' });
    await Promise.all([
      page.waitForNavigation(),
      page.locator('a[href="/my_messages.php"]').click(),
    ]);
    // Enter login credentials and login
    page.locator('input[name="login"]').type('admin');
    page.locator('input[name="password"]').type('123');
    // We expect the form submission to trigger a navigation, so to prevent a
    // race condition, setup a waiter concurrently while waiting for the click
    // to resolve.
    await Promise.all([
      page.waitForNavigation(),
      page.locator('input[type="submit"]').click(),
    ]);
    check(page, {
      'header': page.locator('h2').textContent() == 'Welcome, admin!',
    });
  } finally {
    page.close();
  }
}
```

we sometimes see the following error:

```bash
Uncaught (in promise) GoError: creating new page in browser context: timed out after 30s
	at github.com/grafana/xk6-browser/browser.mapBrowserContext.func4 (native)
	at file:///tmp/TgCEDu/script.js:24:15(8)
 executor=shared-iterations scenario=ui
```

This doesn't occur when running against a locally running chrome instance.

### Expected behaviour

We don't see those timeouts when a new page is being created.

### Actual behaviour

We are seeing `creating new page in browser context: timed out after 30s`

**Comment by ankur22** [comment]
Take a look at https://github.com/grafana/xk6-browser/issues/970 for the conclusion as to why this is occurring for this particular case.

**Comment by inancgumus** [comment]
Closed by #1219.
